### PR TITLE
Release v1.0

### PR DESCRIPTION
**Pull request by khalidbahri**
Including a detailed pull request body

### CODE REVIEW

**Review by khalidbahri — COMMENTED** [review]
Jawad, I have reviewed the changes.  

Thanks & Regards, 
Khalid.

**Review by Jkhan9441 — APPROVED** [review]
Approved!

**Review by khalidbahri — COMMENTED** [review]
closed

**Review by Jkhan9441 — APPROVED** [review]
Approved!

**Review by khalidbahri — COMMENTED** [review]
Approving

**Review by khalidbahri — COMMENTED** [review]
Testing

**Comment by khalidbahri** [comment]
Merged

**Pull request merged**
